name: Keep Active

on:
  schedule:
    - cron: '0 */2 * * 1-5'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Отключаем GITHUB_TOKEN
          fetch-depth: 0

      - name: Make commit and push
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          # Используем PAT для всех операций с Git
          git config --global user.name "Hornglihearth"
          git config --global user.email "270450827+Hornglihearth@users.noreply.github.com"

          # Обновляем URL удаленного репозитория
          git remote set-url origin https://x-access-token:${PAT}@github.com/Hornglihearth/TelegramFix.git

          # Вносим изменения
          echo "$(date) - Keep active" >> activity.log
          git add activity.log

          # Проверяем, есть ли изменения для коммита
          if git diff --cached --quiet; then
            echo "Нет новых изменений для коммита."
            exit 0
          fi

          # Создаем коммит и отправляем
          git commit -m "chore: periodic update"
          git pull --rebase origin main
          git push origin main
